USE tnea_guider;

INSERT INTO districts (name) VALUES
('Ariyalur'), ('Chengalpattu'), ('Chennai'), ('Coimbatore'), ('Cuddalore'),
('Dharmapuri'), ('Dindigul'), ('Erode'), ('Kanchipuram'), ('Kanyakumari'),
('Karur'), ('Kallakurichi'), ('Krishnagiri'), ('Madurai'), ('Mayiladuthurai'),
('Nagapattinam'), ('Namakkal'), ('Perambalur'), ('Pudukkottai'), ('Ramanathapuram'),
('Ranipet'), ('Salem'), ('Sivaganga'), ('Tanjore'), ('Thanjavur'), ('Thoothukudi'),
('Tiruchirappalli'), ('Tirunelveli'), ('Tiruppur'), ('Tiruvallur'), ('Tiruvannamalai'),
('Tiruvarur'), ('Vellore'), ('Villupuram');

INSERT INTO colleges (name, district_id, tier) VALUES
('Adhiparasakthi Engineering College', (SELECT id FROM districts WHERE name='Chengalpattu'), 'Tier 3'),
('Karpaga Vinayaga College of Engineering and Technology', (SELECT id FROM districts WHERE name='Chengalpattu'), 'Tier 3'),
('SRM Valliammai Engineering College', (SELECT id FROM districts WHERE name='Chengalpattu'), 'Tier 2'),
('SSN College of Engineering', (SELECT id FROM districts WHERE name='Chengalpattu'), 'Tier 1'),
('Agni College of Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Anand Institute of Higher Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Apollo Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Asan Memorial College of Engineering and Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Chennai Institute of Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Chennai Institute of Technology and Applied Research', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('College of Engineering Guindy', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 1'),
('Dhaanish Ahmed College of Engineering', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('Dhanalakshmi College of Engineering', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('Easwari Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('GKM College of Engineering and Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('Jerusalem College of Engineering', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('KCG College of Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Madras Institute of Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 1'),
('Meenakshi College of Engineering', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('Meenakshi Sundararajan Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('Misrimal Navajee Munoth Jain College of Engineering', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('Rajalakshmi Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Rajalakshmi Institute of Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('SA Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Sri Sai Ram Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('Sri Sai Ram Institute of Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('St. Joseph''s College of Engineering', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 3'),
('St. Joseph''s Institute of Technology', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Vel Tech High Tech Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Vel Tech Multi Tech Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Velammal Engineering College', (SELECT id FROM districts WHERE name='Chennai'), 'Tier 2'),
('Adithya Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Akshaya College of Engineering & Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('Coimbatore Institute of Engineering and Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('Coimbatore Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 1'),
('Dr. Mahalingam College of Engineering and Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Dr. NGP Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('Government College of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 1'),
('Hindusthan College of Engineering and Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Hindusthan Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Jansons Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Karpagam College of Engineering', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Karpagam Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Kumaraguru College of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Nehru Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('Park College of Engineering and Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('Pollachi Institute of Engineering and Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('PSG College of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 1'),
('PSG Institute of Technology and Applied Research', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('SNS College of Engineering', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('SNS College of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Sri Eshwar College of Engineering', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Sri Krishna College of Engineering and Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 1'),
('Sri Krishna College of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('Sri Ramakrishna Engineering College', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 3'),
('Sri Ramakrishna Institute of Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Sri Shakthi Institute of Engineering and Technology', (SELECT id FROM districts WHERE name='Coimbatore'), 'Tier 2'),
('Al-Ameen Engineering College', (SELECT id FROM districts WHERE name='Erode'), 'Tier 2'),
('Bannari Amman Institute of Technology', (SELECT id FROM districts WHERE name='Erode'), 'Tier 2'),
('Builders Engineering College', (SELECT id FROM districts WHERE name='Erode'), 'Tier 3'),
('Erode Sengunthar Engineering College', (SELECT id FROM districts WHERE name='Erode'), 'Tier 2'),
('Government College of Engineering Erode', (SELECT id FROM districts WHERE name='Erode'), 'Tier 2'),
('Kongu Engineering College', (SELECT id FROM districts WHERE name='Erode'), 'Tier 1'),
('Nandha Engineering College', (SELECT id FROM districts WHERE name='Erode'), 'Tier 2'),
('Velalar College of Engineering and Technology', (SELECT id FROM districts WHERE name='Erode'), 'Tier 2'),
('Adhi College of Engineering and Technology', (SELECT id FROM districts WHERE name='Kanchipuram'), 'Tier 2'),
('Jeppiaar Engineering College', (SELECT id FROM districts WHERE name='Kanchipuram'), 'Tier 2'),
('Jeppiaar Institute of Technology', (SELECT id FROM districts WHERE name='Kanchipuram'), 'Tier 2'),
('Loyola ICAM College of Engineering and Technology', (SELECT id FROM districts WHERE name='Kanchipuram'), 'Tier 3'),
('Saveetha Engineering College', (SELECT id FROM districts WHERE name='Kanchipuram'), 'Tier 2'),
('Sri Venkateswara College of Engineering', (SELECT id FROM districts WHERE name='Kanchipuram'), 'Tier 3'),
('Amrita College of Engineering and Technology', (SELECT id FROM districts WHERE name='Kanyakumari'), 'Tier 2'),
('St. Xavier''s Catholic College of Engineering', (SELECT id FROM districts WHERE name='Kanyakumari'), 'Tier 2'),
('Annai Mathammal Sheela Engineering College', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('Excel Engineering College', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('Gnanamani College of Technology', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('JKK Munirajah College of Technology', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('JKK Nataraja College of Engineering and Technology', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 3'),
('KSR College of Engineering', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('KSR College of Technology', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('Mahendra Engineering College', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 3'),
('Mahendra Institute of Technology', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('Muthayammal Engineering College', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 3'),
('Paavai Engineering College', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('Sengunthar Engineering College', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('Vivekanandha College of Engineering for Women', (SELECT id FROM districts WHERE name='Namakkal'), 'Tier 2'),
('A V S Engineering College', (SELECT id FROM districts WHERE name='Salem'), 'Tier 2'),
('Annapoorana Engineering College', (SELECT id FROM districts WHERE name='Salem'), 'Tier 2'),
('Dhirajlal Gandhi College of Technology', (SELECT id FROM districts WHERE name='Salem'), 'Tier 2'),
('Government College of Engineering Salem', (SELECT id FROM districts WHERE name='Salem'), 'Tier 2'),
('Sona College of Technology', (SELECT id FROM districts WHERE name='Salem'), 'Tier 2'),
('CARE College of Engineering', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 3'),
('Government College of Engineering Srirangam', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 2'),
('Indra Ganesan College of Engineering', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 3'),
('JJ College of Engineering and Technology', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 3'),
('K Ramakrishnan College of Engineering', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 2'),
('Kongunadu College of Engineering and Technology', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 3'),
('MIET Engineering College', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 3'),
('Saranathan College of Engineering', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 3'),
('SRM TRP Engineering College', (SELECT id FROM districts WHERE name='Tiruchirappalli'), 'Tier 2'),
('Aalim Muhammed Salegh College of Engineering', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 3'),
('Alpha College of Engineering', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 2'),
('GRT Institute of Engineering and Technology', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 3'),
('Jaya Engineering College', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 3'),
('Panimalar Engineering College', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 2'),
('Prathyusha Engineering College', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 2'),
('RMK College of Engineering and Technology', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 2'),
('RMK Engineering College', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 1'),
('RMD Engineering College', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 3'),
('Velammal Institute of Technology', (SELECT id FROM districts WHERE name='Tiruvallur'), 'Tier 3'),
('A K T Memorial College', (SELECT id FROM districts WHERE name='Kallakurichi'), 'Tier 2'),
('A R J College', (SELECT id FROM districts WHERE name='Tiruvarur'), 'Tier 2'),
('Anjalai Ammal Mahalingam College', (SELECT id FROM districts WHERE name='Tiruvarur'), 'Tier 2'),
('AVC College', (SELECT id FROM districts WHERE name='Mayiladuthurai'), 'Tier 2'),
('Adhiyamaan College', (SELECT id FROM districts WHERE name='Krishnagiri'), 'Tier 2'),
('Government College Bargur', (SELECT id FROM districts WHERE name='Krishnagiri'), 'Tier 2'),
('Alagappa Chettiar College', (SELECT id FROM districts WHERE name='Sivaganga'), 'Tier 2'),
('KLN College', (SELECT id FROM districts WHERE name='Sivaganga'), 'Tier 3'),
('Angel College', (SELECT id FROM districts WHERE name='Tiruppur'), 'Tier 2'),
('Jai Shriram College', (SELECT id FROM districts WHERE name='Tiruppur'), 'Tier 3'),
('Arasu Engineering College', (SELECT id FROM districts WHERE name='Thanjavur'), 'Tier 2'),
('Government College Thanjavur', (SELECT id FROM districts WHERE name='Thanjavur'), 'Tier 2'),
('Arunai Engineering College', (SELECT id FROM districts WHERE name='Tiruvannamalai'), 'Tier 2'),
('Abdul Hakeem College', (SELECT id FROM districts WHERE name='Ranipet'), 'Tier 3'),
('CK College', (SELECT id FROM districts WHERE name='Cuddalore'), 'Tier 3'),
('Dhanalakshmi Srinivasan College', (SELECT id FROM districts WHERE name='Perambalur'), 'Tier 3'),
('Roever College', (SELECT id FROM districts WHERE name='Perambalur'), 'Tier 3'),
('EGS Pillay College', (SELECT id FROM districts WHERE name='Nagapattinam'), 'Tier 2'),
('Francis Xavier College', (SELECT id FROM districts WHERE name='Tirunelveli'), 'Tier 2'),
('Government College Tirunelveli', (SELECT id FROM districts WHERE name='Tirunelveli'), 'Tier 2'),
('Government College Dharmapuri', (SELECT id FROM districts WHERE name='Dharmapuri'), 'Tier 2'),
('IFET College', (SELECT id FROM districts WHERE name='Villupuram'), 'Tier 2'),
('Mailam College', (SELECT id FROM districts WHERE name='Villupuram'), 'Tier 3'),
('Chettinad College', (SELECT id FROM districts WHERE name='Karur'), 'Tier 3'),
('Kumarasamy College', (SELECT id FROM districts WHERE name='Karur'), 'Tier 2'),
('Mohamed Sathak College', (SELECT id FROM districts WHERE name='Ramanathapuram'), 'Tier 3'),
('Mookambigai College', (SELECT id FROM districts WHERE name='Pudukkottai'), 'Tier 3'),
('National Engineering College', (SELECT id FROM districts WHERE name='Thoothukudi'), 'Tier 2'),
('PSNA College', (SELECT id FROM districts WHERE name='Dindigul'), 'Tier 2'),
('Thiagarajar College', (SELECT id FROM districts WHERE name='Madurai'), 'Tier 1');

INSERT INTO branches (name) VALUES
('CSE'), ('IT'), ('ECE'), ('EEE'), ('MECH'), ('CIVIL'), ('AI & DS'), ('AI & ML');

INSERT INTO categories (name) VALUES
('OC'), ('BC'), ('BCM'), ('MBC'), ('SC'), ('SCA'), ('ST');

INSERT INTO cutoff_data (college_id, branch_id, category_id, cutoff, fees, placement_rate)
SELECT c.id, b.id, cat.id,
ROUND(150 + RAND() * 45, 1) as cutoff,
ROUND(50000 + RAND() * 80000, 0) as fees,
ROUND(40 + RAND() * 50, 0) as placement_rate
FROM colleges c
CROSS JOIN branches b
CROSS JOIN categories cat;