server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/tnea_guider
spring.datasource.username=root
spring.datasource.password=vrki1005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=AIzaSyDGK5OySEkdxhrYNph-O_AVV4cyZtxkugs

